# Generated by Django 5.1.2 on 2025-01-02 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0003_alter_lead_age_alter_lead_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="comment",
            field=models.TextField(blank=True, null=True),
        ),
    ]
