# Generated by Django 5.1.2 on 2025-01-04 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0004_lead_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="convert",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="lead",
            name="phone_number",
            field=models.CharField(default="123456789", max_length=15),
            preserve_default=False,
        ),
    ]
