# Generated by Django 5.1.2 on 2024-12-07 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0002_initial"),
        ("leads", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contact",
            name="agent",
        ),
        migrations.AddField(
            model_name="contact",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="leads.userprofile",
            ),
        ),
    ]
