# Generated by Django 5.1.2 on 2025-01-05 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="age",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
