# Generated by Django 5.1.2 on 2024-12-07 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0003_remove_contact_agent_contact_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="status",
            field=models.CharField(
                choices=[("Regular", "Regular"), ("Important", "Important")],
                default="Regular",
                max_length=20,
            ),
        ),
    ]
