# Generated by Django 5.1.2 on 2024-12-20 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_alter_order_date_created"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="discount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Discount percentage",
                max_digits=5,
            ),
        ),
    ]
