# Generated by Django 5.1.2 on 2025-01-05 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0005_remove_order_payment_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="status_history",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Accepted", "Accepted"),
                    ("Canceled", "Canceled"),
                    ("Paid", "Paid"),
                ],
                default="Pending",
                max_length=20,
            ),
        ),
    ]
