# Generated by Django 5.1.2 on 2025-01-06 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_pricehistory"),
    ]

    operations = [
        migrations.AddField(
            model_name="pricehistory",
            name="revenue_in_week",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="pricehistory",
            name="units_sold_in_week",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
