# Generated by Django 5.1.2 on 2025-01-06 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_pricehistory_revenue_in_week_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pricehistory",
            name="revenue_in_week",
        ),
        migrations.RemoveField(
            model_name="pricehistory",
            name="units_sold_in_week",
        ),
    ]
