# Generated by Django 5.1.2 on 2025-01-11 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_remove_pricehistory_revenue_in_week_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="clients",
        ),
    ]
